import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { TRPCProvider } from "@/utils/providers/TrpcProviders";
import { MainLayout } from "@/app/main-layout";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500",],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar:state")?.value === "true"

  return (
    <html lang="en">
      <body className={` ${poppins.variable} `}
      >
      <TRPCProvider>
        <SidebarProvider defaultOpen={defaultOpen}>
          <MainLayout>
            {children}
          </MainLayout>
          <Toaster />
        </SidebarProvider>
      </TRPCProvider>
      </body>
    </html>
  );
}
